"""Per-repository template for tools/build_notebook.py (NOTEBOOK_SPEC 2.2 §4 standalone carrier).

Only the task-specific prose and stage cells live here. Runtime install, the embedded package (three modules,
carried verbatim in dependency order), and the model pin/stage/verify cells are produced by the generator from
repository sources so they cannot drift from the package.

This template configures an E2E open-vocabulary detection fine-tuning workflow: the pinned
IDEA-Research/grounding-dino-tiny snapshot is digest-verified and loaded, the 364 MIT-licensed BCCD blood-smear
photographs are fetched with per-file digests (their 4,886 boxes over three cell types travel inline), the records are
validated and split by image, a synthetic scene is detected through the inference contract, the frozen model's
per-phrase AP over the held-out images is measured beside a grid prior and a generic-prompt baseline, a bounded
fine-tuning of the cross-modality decoder and the heads runs with the upstream Hungarian criterion, the held-out split
is scored again per phrase, the scene and four held-out images are re-detected with the adapted model, and the adapter
is exported and reloaded.

Review fixes (Notebook Review Framework v1, review PR #11, GDD-M1..M4 / GDD-m1..m4): the runtime is the fleet's uv
isolated environment (no in-kernel install, no restart); Sections 5-7 start from the pretrained model on every re-run
and `adapt` refuses an adapted pipeline, so a documented experiment or a BYOD re-run never reads the adapted model as
"frozen"; BYOD states and checks its real minimum (12 distinct images), names the split it refuses, reports dropped
duplicates, refuses duplicate file names and oversized archives, takes a path as well as an upload and explains a
cancelled upload; the generic-prompt baseline word is a form field and the comparisons are recorded, not asserted;
worked answers quote the recorded Kaggle Tesla T4 run and the run-to-run spread is stated; the notebook says it builds
its own Python 3.12.12 environment whatever the kernel runs; and the guided layer (audience, task contract, how to use,
roadmap, predictions, worked answers, a change-one-thing activity, troubleshooting, glossary, conclusion) is added with
the setup cells labelled Infrastructure and collapsed.
"""
# ruff: noqa: E501  -- markdown prose and code-cell text are kept on single lines for readable rendering

TEMPLATE = {
    "package": "grounding_dino_detection_pipeline",
    "repo_name": "grounding-dino-detection-pipeline",
    "stem": "grounding_dino_detection",
    "notebook_name": "grounding_dino_detection_colab.ipynb",
    "profile": "E2E",
    "mode": "GUIDED",
    "infrastructure_labels": True,
    "collapse_model_cell": True,
    "isolated_runtime": True,
    # The fleet's uv isolated-environment mechanism (ast-audio-classification-pipeline / bioclip2-biodiversity-pipeline):
    # managed CPython, a size- and SHA-256-verified uv wheel, and a lock compiled from the pyproject pins with
    # `uv pip compile pyproject.toml -c <detr-detection-pipeline lock @ c3c81cb, versions only> --python-version 3.12
    # --python-platform x86_64-manylinux_2_28 --generate-hashes --only-binary :all: -o tutorials/requirements-colab.lock.txt`.
    # The pins equal detr-detection-pipeline's without timm, so the lock is that repository's (Colab T4 PASS at c3c81cb)
    # minus timm: every one of its 48 entries has the same version and hashes there.
    "managed_python": "3.12.12",
    "uv": {
        "version": "0.12.15",
        "url": "https://files.pythonhosted.org/packages/1e/fd/432451d732917c49152a291de3ef171aa6b0f1a22d39780fb2c1f085ca4c/uv-0.12.15-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
        "bytes": 20081404,
        "sha256": "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60",
    },
    "lock": "tutorials/requirements-colab.lock.txt",
    "pipeline_class": "GroundingDINOPipeline",
    "weights_key": "grounding-dino-tiny",
    "modules": ["pipeline.py", "metrics.py", "samples.py"],
    "runtime_imports": ["torch", "transformers"],
    "title": "Grounding DINO tiny — DIMER E2E open-vocabulary detection fine-tuning tutorial (standalone)",
    "badges": [
        (
            "GitHub",
            "https://img.shields.io/badge/GitHub-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/kurtvalcorza/grounding-dino-detection-pipeline",
        ),
        (
            "Open In Colab",
            "https://colab.research.google.com/assets/colab-badge.svg",
            "https://colab.research.google.com/github/kurtvalcorza/grounding-dino-detection-pipeline/blob/main/tutorials/grounding_dino_detection_colab.ipynb",
        ),
        (
            "Hugging Face",
            "https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-IDEA--Research%2Fgrounding--dino--tiny-ffcc4d?style=flat",
            "https://huggingface.co/IDEA-Research/grounding-dino-tiny",
        ),
        (
            "Upstream",
            "https://img.shields.io/badge/Upstream-IDEA--Research%2FGroundingDINO-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/IDEA-Research/GroundingDINO",
        ),
        ("arXiv", "https://img.shields.io/badge/arXiv-2303.05499-b31b1b.svg", "https://arxiv.org/abs/2303.05499"),
    ],
    "capability": "zero-shot (open-vocabulary, text-prompted) object detection and bounded supervised fine-tuning of the cross-modality decoder on labelled boxes with a phrase vocabulary, using the pinned `IDEA-Research/grounding-dino-tiny` weights",
    "run_all": (
        "Selecting **Run all** in a fresh supported runtime builds an isolated environment from the hash-locked pins (the "
        "kernel's own packages are left alone, so no restart is needed), stages and digest-verifies the "
        "pinned `IDEA-Research/grounding-dino-tiny` snapshot (a 689 MB `model.safetensors`; no pickle is opened anywhere), "
        "fetches the 364 pinned BCCD blood-smear photographs from GitHub's raw-content host at an immutable commit (about "
        "7.6 MB, each refused on any byte-size or SHA-256 mismatch; their 4,886 boxes travel inline), validates them against "
        "the three-phrase vocabulary and splits them by image into 220 / 50 / 94, detects a synthetic scene through the "
        "inference contract with an input manifest and a rejection probe, measures the frozen model's per-phrase AP50 and "
        "AP75 over the 94 held-out images beside a grid prior and a generic-prompt baseline, runs a bounded fine-tuning of "
        "the cross-modality decoder and the box / contrastive heads with the upstream Hungarian criterion and validation-mAP50 "
        "epoch selection, scores the held-out images again per phrase, re-detects the scene and four held-out images with "
        "the adapted model, exports the adapter as safetensors with a manifest, and reloads that artifact into a fresh "
        "pipeline to verify box parity. The default path needs no repository clone, no DIMER worker or service, no "
        "credential, no upload dialog and no configuration edit (NOTEBOOK_SPEC 2.2 §5). A CUDA runtime is used "
        "automatically when present, and **a GPU runtime is required in practice**: in the recorded Kaggle Tesla T4 run "
        "of the previous notebook version (same model stages) the six epochs took 931 s and the whole run about 25 "
        "minutes including the downloads, while a CPU runtime would take hours (Swin-T + BERT at 800-px inputs for 55 "
        "training steps per epoch, each over four images, plus a validation pass per epoch). Building the isolated "
        "environment comes on top of this."
    ),
    "byod": (
        "After the tutorial workflow completes, set `USE_BYOD = True` in Section 4, select that cell and choose **Runtime → "
        "Run after** (it re-runs Section 4 and every later cell; Sections 5, 6 and 7 reload the pretrained model first, so "
        "the earlier adaptation never carries over into a *frozen* number). Supply one zip through the upload dialog on "
        "Colab, or a zip or folder path in `BYOD_PATH` on any runtime. It holds images plus a `boxes.csv` (`file`, `x0`, "
        "`y0`, `x1`, `y1`, `phrase`; one row per box, at most 16 distinct phrases); the distinct phrases become the prompt "
        "vocabulary. The archive is read without its folders, so every file name must be unique. It needs **at least 12 "
        "distinct images**: the seeded split keeps 20 % for test and 15 % for validation and must leave at least 8 "
        "training, 2 validation and 2 test images; Section 4 checks this before any model runs, names the split it "
        "refuses, and reports any pixel-duplicate images it drops. The records pass through the same validation, "
        "image-disjoint split, baselines, fine-tuning, held-out evaluation, artifact export and reload-parity cells as the "
        "BCCD sample; a result where the adapted model does not beat the frozen one is reported, not treated as an error. "
        "Uploaded files stay inside this runtime. BYOD is optional and never part of the default path."
    ),
    "intro": (
        "`IDEA-Research/grounding-dino-tiny` is the Grounding DINO model of Liu et al. (2023) in its smallest published "
        "size: a Swin-T image backbone and a BERT text encoder fused by a feature enhancer, a language-guided query "
        "selection that picks 900 proposals, and a cross-modality decoder whose queries are scored against every token of "
        "the prompt (172,249,090 parameters, of which the decoder and its heads are 11,187,460; published under the "
        "**Apache-2.0** licence). A box's score is the **sigmoid** of its alignment with a phrase's tokens — a grounding "
        "score, not a calibrated probability.\n\n"
        "What this notebook adds to inference is **adaptation with a labelled vocabulary**. An open-vocabulary detector "
        "grounds the words it was trained around; the blood-smear photographs of the BCCD dataset — red blood cells, white "
        "blood cells and platelets under a microscope — are a domain its training captions barely name, and on them the "
        "frozen model reaches a mean AP50 of only **0.109** (the recorded Kaggle Tesla T4 run on the 94 held-out images: "
        "0.04 for `red blood cell`, 0.29 for `white blood cell`, 0.00 for `platelet`) against 0.009 for a grid of mean-sized "
        "boxes and 0.075 for the model's own boxes for the generic word `cell` relabelled to the majority phrase. So the "
        "honest question is narrow: does a bounded fine-tuning of the decoder and the heads on 220 labelled images move the "
        "held-out **AP50** and **AP75** on an image-disjoint test split, per phrase, past those two **non-adapted "
        "baselines** and the frozen model? Nothing here is a claim about your images or your vocabulary: it is one seeded "
        "split of one small labelled set.\n\n"
        "**Snapshot note:** the pinned revision ships `model.safetensors` (a 9-file manifest with the tokenizer files) — no "
        "pickle is opened anywhere in this notebook. Section 3 stages and digest-verifies those files before the processor or "
        "the model is constructed.\n\n"
        "**Who this is for.** A learner who knows basic Python, NumPy and PIL, has met bounding boxes and the idea of a "
        "pretrained model, and wants to see how an open-vocabulary detector is measured on labelled boxes and adapted to a "
        "new vocabulary. No prior experience with Grounding DINO, detection metrics or fine-tuning is assumed; each term is "
        "explained where it is first used and again in the **Glossary** at the end. A **GPU runtime** (for example a Colab "
        "or Kaggle T4) is needed in practice (Prerequisites).\n\n"
        "**Input → Model → Output.**\n\n"
        "| | Inference | Fine-tuning |\n"
        "|---|---|---|\n"
        "| Input | one image (16 to 4,096 px a side) and 1 to 16 text phrases, each at most 48 characters | 220 training photographs, each with its labelled boxes and the phrase of each box |\n"
        "| Model | Grounding DINO tiny: Swin-T image backbone + BERT text encoder → feature enhancer → 900 queries → cross-modality decoder scored against the phrase tokens | the same model with the decoder and the box / contrastive heads trained (11.2 M of 172.2 M parameters), everything else frozen |\n"
        "| Output | boxes in pixel coordinates, each with the phrase it grounds to and a sigmoid grounding score — not a probability | an adapter (safetensors) and held-out per-phrase AP50 / AP75 beside two baselines and the frozen model |\n\n"
        "**How to use this notebook.** Choose a GPU runtime, then **Runtime → Run all**. Sections 1–3 are **infrastructure** "
        "— the isolated environment, the carried code and the model verification — and can be run without study; their "
        "code is collapsed. The learning path starts in Section 4. Form fields (`# @param`) are the only values meant to be "
        "edited; the defaults reproduce the recorded path. Each stage asks you to **predict** before it runs, and the next "
        "cell opens with **What to notice** and a collapsible **Check your reasoning** block with a worked answer from the "
        "recorded Kaggle Tesla T4 run of the previous notebook version (same model stages; your GPU's numbers can differ, "
        "and training results by a few hundredths — see **Run-to-run spread** in Section 7). Each optional experiment names "
        "the cell to change and the cells to re-run. Section 10 is a **change-one-thing activity**. **Troubleshooting**, a "
        "**Glossary** and a **Conclusion** template are at the end. Your notes are optional and are not required "
        "submissions.\n\n"
        "**Roadmap:** 4 fetch, validate and split the photographs → 5 detect a synthetic scene with the pretrained model → "
        "6 two baselines and the pretrained model on the test images → 7 fine-tune the decoder and the heads → 8 compare on "
        "the held-out images → 9 look at the boxes, export and reload → 10 **change one thing: a lower learning rate** → "
        "conclude. Core concepts are Sections 5 and 6 (what the model emits and how it is scored); evaluation practice is "
        "Sections 4, 7 and 8 (split, selection, held-out comparison); engineering and reproducibility are Sections 1–3 and 9."
    ),
    "learning_objectives": (
        "by the end you should be able to (1) explain *image + phrases → 900 queries → per-phrase grounding scores → boxes* "
        "and say why a grounding score is not a probability (Section 5); (2) read per-phrase AP50 and AP75 against a grid "
        "prior and a generic-prompt baseline, and say what each baseline rules out (Section 6); (3) explain how the "
        "validation split, never the test split, chooses the kept epoch (Section 7); (4) predict and then check how mAP50, "
        "mAP75 and each phrase move after a bounded fine-tuning, and say why the rarest, smallest phrase gains least "
        "(Section 8); (5) say what an image-disjoint split does and does not protect against (Sections 4 and 8); (6) check "
        "that an exported adapter reproduces the evaluated model (reload parity, Section 9); and (7) predict and then "
        "observe what a lower learning rate changes (Section 10)."
    ),
    "exclusions": (
        "instance or semantic segmentation (see the sibling SAM pipelines), tracking, OCR, captioning, closed-set detection "
        "with a fixed class head (the vocabulary stays text), fine-tuning of the image backbone, the text encoder, the "
        "feature enhancer or the query selection, COCO-style AP averaged over IoU 0.5..0.95 (only AP50 and AP75 are computed), "
        "evaluation on COCO, LVIS, ODinW or any benchmark proper (only one seeded 364-image sample is scored here), and any "
        "claim that three blood-cell phrases stand in for your vocabulary. The repository exposes none of these."
    ),
    "prerequisites": [
        "- **Learner:** basic Python, NumPy and PIL, and Colab or Jupyter familiarity; what a bounding box in xyxy pixel coordinates is. No prior experience with Grounding DINO, detection metrics or fine-tuning: the notebook explains grounding scores, IoU, AP50 / AP75, the two baselines, Hungarian matching and validation-based epoch selection where they are first used, and the Glossary repeats them.",
        "- **Runtime:** a fresh **Linux x86_64** runtime with a CUDA GPU — Google Colab, Kaggle or Linux Jupyter. Section 1 builds its own **Python 3.12.12** environment from a hash-locked list of manylinux wheels, so the kernel's own Python version does not matter (Colab's kernel runs Python 3.13 as of September 2026; the stages still run on 3.12.12), and a Windows or macOS kernel is not supported (Section 1 stops with that message). The default path uses CUDA automatically when present. In the recorded Kaggle Tesla T4 run of the previous notebook version (same model stages, Python 3.12.13 in the kernel) the six epochs with per-epoch validation took 931 s and the whole run 1,504 s including about 700 MB of downloads; a CPU runtime would take hours. The locked install (PyTorch 2.14.0 with its CUDA libraries, a few GB) and the 689 MB checkpoint are the large downloads of the run; the photographs are about 7.6 MB.",
        "- **Data contract:** records are `{id, image, boxes, labels}` — `image` a PIL image (or a file decodable by Pillow) with sides within 16..4096 px, `boxes` one or more `[x0, y0, x1, y1]` pixel boxes inside it (at most 300), `labels` one phrase per box drawn from the prompt vocabulary (1..16 distinct phrases of at most 48 characters each, given beside the records). Ids match `[A-Za-z0-9_.:-]{1,64}` and are unique; a training split needs 8..5,000 records. Splitting de-duplicates by decoded pixels so no image lands in two splits, and the seeded BYOD split (65 / 15 / 20 %) must leave at least 8 training, 2 validation and 2 test images, so **a BYOD dataset needs at least 12 distinct images** (Section 4 computes and prints this minimum, checks it before any model runs and names the split it refuses).",
        "- **BYOD layout:** one zip (by upload on Colab, or by path in `BYOD_PATH` on any runtime; a folder path also works) holding the images and a `boxes.csv` with the columns `file`, `x0`, `y0`, `x1`, `y1`, `phrase` (one row per box). The archive is read without its folders, so every file name must be unique; two files with one name are refused with a message naming both. An archive of more than 10,000 files or more than 1 GB once expanded is refused before anything is decompressed.",
        "- **Validation is structural, not semantic:** every image is decoded and every box and phrase checked against the image and the vocabulary, but nothing checks that a box outlines what its phrase says — a mislabelled set is fine-tuned on without complaint.",
        "- **Privacy:** Do not upload confidential or restricted data to a hosted runtime unless you are authorized to process it there. The default path uploads nothing.",
        "- **External access (data):** besides the model snapshot, the default path fetches 364 JPEG files from `https://raw.githubusercontent.com/Shenggan/BCCD_Dataset/<commit>/BCCD/JPEGImages/` at the immutable commit `d272fb14…` (about 7.6 MB in total), each pinned by byte size and SHA-256 in the carried `samples.py` and refused on any mismatch; the boxes (the repository's Pascal VOC annotations at the same commit, two zero-area boxes dropped) travel inline. BCCD is published under the MIT licence; nothing is redistributed by this repository.",
    ],
    "cells": [
        {
            "md": (
                "## 4. BCCD photographs, the phrase vocabulary and the split\n\n"
                "`fetch_corpus` returns the 364 pinned photographs from the cache under `weights/bccd/` or GitHub's raw-content "
                "host at the pinned commit — every cached file is re-hashed and every fetched file refused on any byte-size or "
                "SHA-256 mismatch — and `read_corpus` turns each into a record with its boxes and the phrase each box is "
                "labelled with; `PROMPTS` is the vocabulary (`red blood cell`, `white blood cell`, `platelet` — the dataset's "
                "class names spelled out as the phrases the detector is prompted with). `build_sample_dataset` draws a seeded "
                "image-level split (220 / 50 / 94). `validate_dataset` then checks every record against the contract and the "
                "vocabulary (each split against its own minimum from `split_minimums()`), `check_split_disjoint` asserts no "
                "image (by decoded-pixel digest) is shared, and the training split's summary table is written to "
                "`outputs/{stem}_train.csv`.\n\n"
                "**What the split does and does not protect against.** No photograph is in two splits, so the test score is never "
                "computed on an image the model trained on. But BCCD comes from one microscope set-up and one staining protocol, "
                "and nothing records which slide or patient a photograph came from, so neighbouring fields of one slide can sit in "
                "training and in test. The held-out scores in Section 8 are therefore an estimate for *more photographs like "
                "these*, not for another laboratory's slides.\n\n"
                "**Bring your own data:** set `USE_BYOD = True`, either leave `BYOD_PATH` empty to get an upload dialog "
                "(Colab only) or set it to a zip or folder already in this runtime, then select this cell and choose **Runtime → "
                "Run after**. An empty or cancelled upload, a runtime without the Colab upload dialog and no `BYOD_PATH`, or a "
                "path that does not exist stops with a message saying what to supply. `load_byod_dataset` refuses two files "
                "with one name (the archive is read without its folders), an archive over its size limits, a missing "
                "`boxes.csv`, a row naming a missing file or a row without a phrase; pixel-duplicate images are counted and named "
                "before the split drops them; and `split_dataset` refuses a dataset that leaves fewer than 8 training, 2 "
                "validation or 2 test images, naming the split (at least 12 distinct images). Under BYOD the printed provenance "
                "and `result.json` describe your upload, not the BCCD corpus.\n\n"
                "Look for: 364 photographs and 4,886 boxes, three digests, the BYOD minimum the code computes, and four refusal "
                "probes — a duplicate id, a box outside its image, a label outside the vocabulary, and a dataset too small to "
                "use — each rejected before the model does anything.\n\n"
                "**Predict before running:** of the boxes in the 94 test images, roughly what share do you expect to be `red "
                "blood cell` — about a third, about half, or most of them? And which phrase do you expect to be rarest?"
            ),
            "code": (
                "import hashlib\n"
                "import json\n"
                "import time\n\n"
                "import numpy as np\n"
                "from PIL import Image, ImageDraw\n\n"
                "USE_BYOD = False  # @param {{type:\"boolean\"}}\n"
                "BYOD_PATH = ''  # @param {{type:\"string\"}}\n"
                "SPLIT_SEED = 42  # @param {{type:\"integer\"}}\n\n"
                "os.makedirs('outputs', exist_ok=True)\n"
                "byod = None\n"
                "if USE_BYOD:\n"
                "    if BYOD_PATH.strip():\n"
                "        byod_source = Path(BYOD_PATH.strip()).expanduser()\n"
                "        if not byod_source.exists():\n"
                "            raise FileNotFoundError(f'BYOD_PATH = {{BYOD_PATH!r}} does not exist in this runtime: fix the path, or leave BYOD_PATH empty to upload a zip in Colab.')\n"
                "        file_name, payload = byod_source.name, (byod_source.read_bytes() if byod_source.is_file() else None)\n"
                "    else:\n"
                "        try:\n"
                "            from google.colab import files\n"
                "        except ImportError:\n"
                "            raise RuntimeError('The upload dialog needs Google Colab. Elsewhere, put the zip (or folder) in this runtime and set BYOD_PATH to its path.') from None\n"
                "        uploaded = files.upload()\n"
                "        if len(uploaded) != 1:\n"
                "            raise ValueError(f'Upload exactly one .zip file (received {{len(uploaded)}}). Run this cell again and choose a file, or set BYOD_PATH to a zip or folder already in this runtime.')\n"
                "        file_name, payload = next(iter(uploaded.items()))\n"
                "        byod_source = Path('work') / 'byod.zip'\n"
                "        byod_source.parent.mkdir(parents=True, exist_ok=True)\n"
                "        byod_source.write_bytes(payload)\n"
                "    records, vocabulary = load_byod_dataset(byod_source)\n"
                "    unique_records, dropped_duplicates = drop_duplicate_images(records)\n"
                "    print({{'byod_records': len(records), 'distinct_images': len(unique_records), 'pixel_duplicates_dropped': len(dropped_duplicates), 'dropped_ids': dropped_duplicates[:20], 'needed': f'at least {{byod_record_limits()[0]}} distinct images'}})\n"
                "    splits = split_dataset(unique_records, vocabulary, seed=SPLIT_SEED)\n"
                "    data_source = 'BYOD (' + file_name + ')'\n"
                "    raw_rows = {{'byod': len(records), 'distinct_images': len(unique_records)}}\n"
                "    byod = {{'file': file_name, 'records': len(records), 'distinct_images': len(unique_records), 'duplicates_dropped': dropped_duplicates, 'zip_sha256': hashlib.sha256(payload).hexdigest() if payload is not None else None}}\n"
                "else:\n"
                "    t0 = time.perf_counter()\n"
                "    corpus_files = fetch_corpus(cache_dir='weights/bccd')\n"
                "    corpus = read_corpus(corpus_files)\n"
                "    vocabulary = list(PROMPTS)\n"
                "    splits = build_sample_dataset(corpus, seed=SPLIT_SEED)\n"
                "    data_source = f'{{CORPUS_NAME}} @ {{CORPUS_COMMIT[:12]}} ({{CORPUS_LICENSE}})'\n"
                "    raw_rows = {{'photographs': len(corpus_files), 'bytes': sum(len(v) for v in corpus_files.values()), 'boxes': sum(len(r['boxes']) for r in corpus), 'seconds': round(time.perf_counter() - t0, 1)}}\n"
                "minimums = split_minimums()\n"
                "dataset_manifests = {{name: validate_dataset(part, vocabulary, min_records=minimums[name]) for name, part in splits.items()}}\n"
                "splits = {{name: manifest['records'] for name, manifest in dataset_manifests.items()}}\n"
                "vocabulary = dataset_manifests['train']['prompts']\n"
                "disjoint = check_split_disjoint(splits)\n"
                "train_records, val_records, test_records = splits['train'], splits['validation'], splits['test']\n"
                "write_dataset_csv(train_records, 'outputs/{stem}_train.csv')\n"
                "print({{'data_source': data_source, 'raw_rows': raw_rows, 'splits': disjoint, 'split_unit': 'photograph (decoded pixels); no slide or patient field', 'vocabulary': vocabulary, 'prompt_text': format_prompts(vocabulary)}})\n"
                "print({{'byod_minimum_distinct_images': byod_record_limits()[0], 'split_minimums': minimums}})\n"
                "for name, manifest in dataset_manifests.items():\n"
                "    print({{name: {{'n': manifest['n_records'], 'boxes': manifest['n_boxes'], 'label_counts': manifest['label_counts'], 'boxes_per_image': manifest['boxes_per_image'], 'digest': manifest['digest'][:16] + '...'}}}})\n"
                "example = train_records[0]\n"
                "print({{'example': {{'id': example['id'], 'image': list(example['image'].size), 'n_boxes': len(example['boxes']), 'first_box': [round(v, 1) for v in example['boxes'][0]], 'first_label': example['labels'][0], 'source': example.get('source')}}}})\n\n"
                "probe_base = (train_records * 8)[:8]\n"
                "probes = {{\n"
                "    'duplicate id': [{{**r, 'id': 'same'}} for r in probe_base],\n"
                "    'box outside its image': [{{**probe_base[0], 'boxes': [[-5.0, 0.0, 20.0, 20.0], *probe_base[0]['boxes'][1:]]}}, *probe_base[1:]],\n"
                "    'label outside the vocabulary': [{{**probe_base[0], 'labels': ['stem cell', *probe_base[0]['labels'][1:]]}}, *probe_base[1:]],\n"
                "    'too small': train_records[:3],\n"
                "}}\n"
                "for name, probe in probes.items():\n"
                "    try:\n"
                "        validate_dataset(probe, vocabulary)\n"
                "        print({{'probe': name, 'verdict': 'accepted'}})\n"
                "    except (TypeError, ValueError) as exc:\n"
                "        print({{'probe': name, 'rejected': str(exc)[:110]}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the three split sizes and box counts, `split_unit`, the BYOD minimum (12), the label counts "
                "per split, and four rejected probes.\n\n"
                "<details><summary>Check your reasoning</summary>Most of them. The 94 test images hold 1,295 boxes: 1,104 `red "
                "blood cell` (85 %), 98 `platelet` and 93 `white blood cell`; the training split has 2,942 boxes in about the same "
                "proportions. A smear has one or two white blood cells per field and many red ones, so `white blood cell` and "
                "`platelet` are the rare phrases — and every average over phrases (mAP) weighs those 93 and 98 boxes as much as "
                "the 1,104. The BYOD minimum the code prints, 12, is the smallest dataset whose seeded 65 / 15 / 20 % split leaves "
                "8 training, 2 validation and 2 test images.</details>\n\n"
                "## 5. Detect a synthetic scene through the inference contract\n\n"
                "The inference contract is exercised as the inference-only tutorial exercised it: a deterministic 320×240 scene "
                "drawn in code — grey background, a dark filled rectangle and a red filled disc — with two prompts naming "
                "them and the drawn boxes kept as references; a different image family from the photographs, and a scene the "
                "adapted model will detect again in Section 9. `validate_inputs` applies exactly the checks `detect` applies "
                "(image sides `MIN_IMAGE_SIDE`..`MAX_IMAGE_SIDE`, 1..`MAX_PROMPTS` phrases of at most `MAX_PROMPT_CHARS`, both "
                "thresholds in `[0, 1]`) and returns an input manifest; an over-long phrase is validated too and its rejection "
                "recorded as a finding. `detect` returns `detections` ordered by descending **sigmoid grounding score** — not a "
                "calibrated probability — each with the phrase it grounded to under the processor's text threshold and its "
                "xyxy box; both thresholds are caller-owned request parameters, not calibrations. The per-image "
                "`evaluation_report` against the self-drawn boxes is `sample-sanity` (`box_iou` per reference: the "
                "**intersection over union** of the detected and the drawn box, 1.0 for a perfect fit) — plumbing evidence, not "
                "a measurement; whether the model is *good at blood cells* is what Section 6 measures on 94 photographs.\n\n"
                "**Every pass starts from the pretrained model.** Section 7 changes the model in memory. If this cell, Section 6 "
                "or Section 7 runs again after Section 7 (a BYOD run or one of the optional experiments), it first reloads the "
                "pretrained model from the verified snapshot with `reset_to_pretrained()`, so a *frozen* number is never read "
                "from the adapted model.\n\n"
                "**Predict before running:** will the pretrained model find both drawn shapes from the phrases `rectangle` and "
                "`red circle`? Which one will get the higher grounding score?"
            ),
            "code": (
                "import gc\n\n\n"
                "def reset_to_pretrained():\n"
                "    \"\"\"Sections 5-7 start from the pretrained model: if an earlier pass adapted `pipe`, reload it from the verified snapshot.\"\"\"\n"
                "    global pipe\n"
                "    if pipe.adapter is None:\n"
                "        return\n"
                "    pipe = None\n"
                "    gc.collect()\n"
                "    if torch.cuda.is_available():\n"
                "        torch.cuda.empty_cache()\n"
                "    pipe = GroundingDINOPipeline.from_pretrained(weights_dir=WEIGHTS_DIR)\n"
                "    print({{'reloaded': 'the pretrained model, from the verified snapshot', 'reason': 'an earlier pass had adapted the model in memory'}})\n\n\n"
                "reset_to_pretrained()\n"
                "scene = Image.new('RGB', (320, 240), (128, 128, 128))\n"
                "draw = ImageDraw.Draw(scene)\n"
                "scene_boxes = {{'rectangle': [40.0, 60.0, 140.0, 180.0], 'red circle': [200.0, 80.0, 280.0, 160.0]}}\n"
                "draw.rectangle(scene_boxes['rectangle'], fill=(30, 30, 30))\n"
                "draw.ellipse(scene_boxes['red circle'], fill=(220, 30, 30))\n"
                "scene_prompts = list(scene_boxes)\n"
                "scene_name = 'synthetic_scene_320x240.png'\n"
                "scene_sha256 = hashlib.sha256(np.asarray(scene).tobytes()).hexdigest()\n"
                "print({{'ceilings': {{'MIN_IMAGE_SIDE': MIN_IMAGE_SIDE, 'MAX_IMAGE_SIDE': MAX_IMAGE_SIDE, 'MAX_PROMPTS': MAX_PROMPTS, 'MAX_PROMPT_CHARS': MAX_PROMPT_CHARS, 'MAX_TEXT_TOKENS': MAX_TEXT_TOKENS, 'BOX_THRESHOLD': BOX_THRESHOLD, 'TEXT_THRESHOLD': TEXT_THRESHOLD, 'SCORE_FLOOR': SCORE_FLOOR, 'MAX_BOXES': MAX_BOXES, 'MIN_RECORDS': MIN_RECORDS, 'MAX_RECORDS': MAX_RECORDS, 'device': pipe.device}}}})\n"
                "input_manifest = validate_inputs(scene, scene_prompts, box_threshold=BOX_THRESHOLD, text_threshold=TEXT_THRESHOLD, names=[scene_name])\n"
                "try:\n"
                "    validate_inputs(scene, ['x' * (MAX_PROMPT_CHARS + 1)])\n"
                "except ValueError as exc:\n"
                "    input_manifest['findings'].append({{'input': 'over-long-prompt-probe', 'verdict': 'rejected', 'message': str(exc)}})\n"
                "with open('outputs/{stem}_input_manifest.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(input_manifest, handle, indent=2, ensure_ascii=False)\n"
                "print({{'scene': scene_name, 'sha256': scene_sha256[:16] + '...', 'manifest_verdict': input_manifest['verdict'], 'findings': len(input_manifest['findings'])}})\n\n\n"
                "def detect_scene(pipeline, label):\n"
                "    started = time.perf_counter()\n"
                "    result = pipeline.detect(scene, scene_prompts, box_threshold=BOX_THRESHOLD, text_threshold=TEXT_THRESHOLD)\n"
                "    elapsed = time.perf_counter() - started\n"
                "    checks = {{\n"
                "        'sorted_by_score': [d['score'] for d in result['detections']] == sorted((d['score'] for d in result['detections']), reverse=True),\n"
                "        'boxes_inside_image': all(0 <= d['box'][0] <= d['box'][2] <= scene.width and 0 <= d['box'][1] <= d['box'][3] <= scene.height for d in result['detections']),\n"
                "        'identity_reported': result['model_id'] == MODEL_ID and result['model_revision'] == MODEL_REVISION,\n"
                "    }}\n"
                "    if not all(checks.values()):\n"
                "        raise RuntimeError(f'detect output failed a sanity check: {{checks}}')\n"
                "    report = evaluation_report(result, scene_boxes, sample_kind='synthetic (authored in this notebook)')\n"
                "    annotated = scene.copy()\n"
                "    marker = ImageDraw.Draw(annotated)\n"
                "    for det in result['detections']:\n"
                "        marker.rectangle(det['box'], outline=(255, 200, 0), width=2)\n"
                "    annotated.save(f'outputs/{stem}_scene_{{label}}.png')\n"
                "    print({{label: {{'seconds': round(elapsed, 3), 'checks': checks, 'detections': [(d['label'], round(d['score'], 3)) for d in result['detections']], 'box_iou': {{m['reference']: round(m['value'], 3) for m in report['metrics']}}, 'verdict': report['verdict']}}}})\n"
                "    return result, report\n\n\n"
                "frozen_scene_result, frozen_scene = detect_scene(pipe, 'frozen')"
            ),
        },
        {
            "md": (
                "**What to notice:** the ceilings line (the caller-owned thresholds), the three `checks`, the score order of the "
                "two detections and their `box_iou`.\n\n"
                "<details><summary>Check your reasoning</summary>Yes, both. In the recorded T4 run `red circle` scored 0.931 and "
                "`rectangle` 0.695, with `box_iou` 0.964 and 0.944 against the drawn boxes: a colour plus a shape word grounds "
                "more confidently than a bare shape word. The scores rank boxes; they are not the probability that the box is "
                "right — a 0.695 box here fits its reference almost as well as the 0.931 one.</details>\n\n"
                "## 6. Baselines and the frozen model on the test images\n\n"
                "Two non-adapted baselines frame the adaptation, each scored by `detection_metrics` (carried in "
                "`metrics.py`): **AP50** and **AP75** — the Pascal-VOC average precision (all-point interpolation, greedy "
                "one-to-one matching in score order) at IoU 0.5 and 0.75 — per phrase and averaged as **mAP50** / **mAP75**, "
                "with the recall at IoU 0.5 over every box kept. The **grid prior** tiles each image with boxes of the "
                "training split's mean size, all labelled with the majority phrase — no model at all, the floor. The "
                "**generic-prompt** baseline asks the frozen model for one generic word (`GENERIC_PROMPT`; empty means `cell` "
                "for the BCCD sample and `object` under BYOD — set it to the generic word for *your* objects) and relabels every "
                "box it returns with the majority phrase — what localisation alone buys without grounding the vocabulary. The "
                "**frozen model** is scored by `pipe.evaluate`, which runs `predict_boxes` on every record: every one of the 900 "
                "queries scored per phrase (the maximum over that phrase's tokens of the query's sigmoid token logits), kept with "
                "its best phrase when that score reaches `SCORE_FLOOR` — the single-phrase-per-box rule the corpus measures use, "
                "distinct from `detect`'s text-threshold labelling. The cell records whether the frozen model beats each "
                "baseline; it does not stop when it does not, because on your own data that can be the honest result.\n\n"
                "**Predict before running:** on blood-cell photographs, will the frozen model's mAP50 land near the two "
                "baselines (below 0.15) or well above them (above 0.4)? Which of the three phrases will it ground best, and "
                "which worst?"
            ),
            "code": (
                "METRICS = ('map50', 'map75', 'recall50')\n"
                "GENERIC_PROMPT = ''  # @param {{type:\"string\"}}\n\n"
                "reset_to_pretrained()\n"
                "generic_prompt = GENERIC_PROMPT.strip() or ('object' if USE_BYOD else 'cell')\n"
                "baseline_grid = grid_prior_baseline(train_records, test_records, vocabulary)\n"
                "print({{'grid_prior_baseline': {{k: round(baseline_grid[k], 3) for k in METRICS}}, 'n': baseline_grid['n'], 'note': baseline_grid['baseline']}})\n"
                "t0 = time.perf_counter()\n"
                "generic_boxes = [pipe.predict_boxes(r['image'], [generic_prompt]) for r in test_records]\n"
                "baseline_generic = majority_relabel_baseline(generic_boxes, train_records, test_records, vocabulary)\n"
                "print({{'generic_prompt_baseline': {{k: round(baseline_generic[k], 3) for k in METRICS}}, 'generic_prompt': generic_prompt, 'note': baseline_generic['baseline'], 'seconds': round(time.perf_counter() - t0, 1)}})\n"
                "t0 = time.perf_counter()\n"
                "frozen_test = pipe.evaluate(test_records, vocabulary)\n"
                "if frozen_test['adapted']:\n"
                "    raise RuntimeError('Section 6 must score the pretrained model, but the model in memory is adapted. Restart the session and choose Run all.')\n"
                "print({{'frozen_model_test': {{k: round(frozen_test[k], 3) for k in METRICS}}, 'n': frozen_test['n'], 'boxes': frozen_test['n_boxes'], 'predictions': frozen_test['n_predictions'], 'adapted': frozen_test['adapted'], 'verdict': frozen_test['verdict'], 'seconds': round(time.perf_counter() - t0, 1)}})\n"
                "print({{'definitions': frozen_test['definitions']}})\n"
                "frozen_fields = {{c: {{'n': v['n'], 'ap50': round(v['ap50'], 3), 'ap75': round(v['ap75'], 3)}} for c, v in frozen_test['per_category'].items()}}\n"
                "print({{'by_phrase_frozen': frozen_fields}})\n"
                "frozen_beats_grid_prior = frozen_test['map50'] > baseline_grid['map50']\n"
                "frozen_beats_generic_prompt = frozen_test['map50'] > baseline_generic['map50']\n"
                "print({{'frozen_beats_grid_prior': frozen_beats_grid_prior, 'frozen_beats_generic_prompt': frozen_beats_generic_prompt}})"
            ),
        },
        {
            "md": (
                "**What to notice:** `adapted: False`, the frozen mAP50 beside the two baselines, the generic word that was "
                "used, and the per-phrase rows.\n\n"
                "<details><summary>Check your reasoning</summary>Near the baselines. In the recorded T4 run the grid prior scored "
                "0.009 mAP50, the generic word `cell` relabelled 0.075 and the frozen model 0.109 (mAP75 0.052, recall 0.293): "
                "`white blood cell` 0.285 best, `red blood cell` 0.041, `platelet` 0.000 — it grounds nothing for the phrase at "
                "all. The generic-prompt baseline reaches a higher recall (0.514) than the frozen model with the real phrases "
                "(0.293): the model *finds* cells, but the three phrases do not steer it to the right ones. That gap is what "
                "adaptation has to close.</details>\n\n"
                "## 7. Bounded fine-tuning of the decoder and the heads\n\n"
                "`pipe.adapt` trains only the cross-modality decoder (its six layers and reference-point head) and the box and "
                "contrastive heads — 11,187,460 of 172,249,090 parameters — while the Swin-T image backbone, the BERT text "
                "encoder, the feature enhancer and the query selection stay frozen. Every image is paired with the formatted "
                "vocabulary (`red blood cell. white blood cell. platelet.`) and each labelled box with the index of its "
                "phrase, and the **upstream Grounding DINO criterion** scores the 900 queries against them: **Hungarian "
                "matching** (each labelled box is paired with the one query that fits it best, one to one), sigmoid-focal "
                "alignment of each matched query to its phrase's tokens (weight 1), L1 (5) and generalised-IoU (2) box terms — "
                "the loss is the checkpoint's own, and its scale (about 11,000) is set by the number of queries and text tokens it "
                "sums over. AdamW without weight decay at a fixed learning rate, gradient clipping at 0.1 (the upstream "
                "recipe's norm), seeded shuffling, no scheduler, no augmentation. Epoch 0 records the frozen model's validation "
                "metrics; every epoch is scored on the 50 validation images, and the epoch with the highest validation mAP50 "
                "is kept. The test images play no part in this choice. `adapt` refuses a pipeline that is already adapted, and "
                "the cell first reloads the pretrained model if an earlier pass adapted it.\n\n"
                "**Run-to-run spread.** GPU training here is not bit-reproducible: the Hungarian matching and the CUDA kernels "
                "make small, order-dependent differences that grow over the 330 training steps. Three recorded GPU runs of this "
                "default recipe on the same split ended at **0.570, 0.608 and 0.632** test mAP50 (an RTX 5070 Ti package-API "
                "run, an RTX 5070 Ti notebook pre-flight and the Kaggle Tesla T4 run quoted in the worked answers). A result a "
                "few hundredths away from the quoted one is that spread, not a fault; the frozen numbers in Sections 5 and 6 "
                "move only in the third decimal between GPUs.\n\n"
                "**Predict before running:** will the validation mAP50 rise in every epoch? Will the training loss fall much?"
            ),
            "code": (
                "EPOCHS = 6  # @param {{type:\"integer\"}}\n"
                "LEARNING_RATE = 5e-5  # @param {{type:\"number\"}}\n"
                "BATCH_SIZE = 4  # @param {{type:\"integer\"}}\n\n\n"
                "def report(entry):\n"
                "    row = {{'epoch': entry['epoch'], 'train_loss': None if entry['train_loss'] is None else round(entry['train_loss'], 1)}}\n"
                "    if entry.get('val'):\n"
                "        row.update({{'val_' + k: round(entry['val'][k], 3) for k in METRICS}})\n"
                "    if 'note' in entry:\n"
                "        row['note'] = entry['note']\n"
                "    print(row)\n\n\n"
                "reset_to_pretrained()\n"
                "t0 = time.perf_counter()\n"
                "adapt_result = pipe.adapt(train_records, val_records, vocabulary, epochs=EPOCHS, lr=LEARNING_RATE, batch_size=BATCH_SIZE, progress=report)\n"
                "adapt_seconds = round(time.perf_counter() - t0, 1)\n"
                "print({{'trainable_parameters': adapt_result['n_trainable'], 'total_parameters': adapt_result['n_total'], 'learning_rate': adapt_result['lr'], 'seed': adapt_result['seed'], 'best_epoch': adapt_result['best_epoch'], 'selection': adapt_result['selection'], 'selection_split': 'validation', 'loss': adapt_result['loss'], 'seconds': adapt_seconds}})"
            ),
        },
        {
            "md": (
                "**What to notice:** epoch 0 is labelled the frozen model, how the training loss and the validation mAP50 move "
                "from epoch to epoch, and which epoch is kept.\n\n"
                "<details><summary>Check your reasoning</summary>Yes, and no. In the recorded T4 run (931 s) the validation "
                "mAP50 rose in every epoch, 0.161 (epoch 0, the frozen model) → 0.319 / 0.426 / 0.516 / 0.577 / 0.637 / 0.692, and "
                "epoch 6 was kept, while the training loss barely moved (11,411 at epoch 1, 11,313 at epoch 6): it is dominated by "
                "the alignment term summed over all 900 queries, most of which match nothing. The decoder is learning to bind "
                "three new phrases to the shapes it already proposes, which 220 images are enough to teach; the loss is not the "
                "number to watch here, the validation mAP50 is. Because the curve was still rising at epoch 6, more epochs might "
                "help — an optional experiment below.</details>\n\n"
                "## 8. Held-out evaluation\n\n"
                "The test images were never used for training or epoch selection, and no image appears in two splits. The "
                "adapted model is scored exactly as the frozen model was in Section 6, the four systems are put side by side "
                "on the three measures, and the per-phrase breakdown is repeated. Read it in this order: **mAP50** first (the "
                "measure the epoch was selected on), then **mAP75** (did the boxes tighten, or only the labels improve?), then "
                "the per-phrase rows. The cell records whether the adapted model beats the frozen one and both baselines, prints "
                "a one-line reading of the outcome and keeps one row per pass in a run history; a result where adaptation did "
                "not help is reported, and the export below still runs. Ninety-four images from one seeded split give **no "
                "dispersion estimate**, and the training itself varies by a few hundredths between runs (Section 7); the deltas "
                "are sample-sanity evidence that the adaptation contract works, not a benchmark, and a gain on three microscope "
                "phrases says nothing about other vocabularies or other imaging until you measure them.\n\n"
                "**Predict before running:** which phrase will gain least from the fine-tuning, and why? Will mAP75 rise as "
                "much as mAP50?"
            ),
            "code": (
                "adapted_test = pipe.evaluate(test_records, vocabulary)\n"
                "adapted_val = pipe.evaluate(val_records, vocabulary)\n"
                "adapted_fields = {{c: {{'n': v['n'], 'ap50': round(v['ap50'], 3), 'ap75': round(v['ap75'], 3)}} for c, v in adapted_test['per_category'].items()}}\n"
                "comparison = {{metric: {{'grid_prior': round(baseline_grid[metric], 3), 'generic_prompt': round(baseline_generic[metric], 3), 'frozen': round(frozen_test[metric], 3), 'adapted': round(adapted_test[metric], 3)}} for metric in METRICS}}\n"
                "comparison['delta_vs_frozen'] = {{metric: round(adapted_test[metric] - frozen_test[metric], 3) for metric in METRICS}}\n"
                "comparison['delta_vs_generic_prompt'] = {{metric: round(adapted_test[metric] - baseline_generic[metric], 3) for metric in METRICS}}\n"
                "comparison['by_phrase'] = {{c: {{'n': frozen_fields[c]['n'], 'frozen_ap50': frozen_fields[c]['ap50'], 'adapted_ap50': adapted_fields[c]['ap50'], 'frozen_ap75': frozen_fields[c]['ap75'], 'adapted_ap75': adapted_fields[c]['ap75']}} for c in frozen_fields}}\n"
                "for key, row in comparison.items():\n"
                "    print({{key: row}})\n\n"
                "# Differences below 0.001 (the printed precision) count as no change.\n"
                "adapted_beats_frozen = comparison['delta_vs_frozen']['map50'] > 0\n"
                "adapted_beats_both_baselines = round(adapted_test['map50'] - max(baseline_grid['map50'], baseline_generic['map50']), 3) > 0\n"
                "if adapt_result['best_epoch'] == 0:\n"
                "    reading = 'The selector kept epoch 0, so the adapted model is the frozen model: no epoch beat it on validation.'\n"
                "elif not adapted_beats_frozen:\n"
                "    reading = f\"The adapted mAP50 is not above the frozen mAP50 on the test images (delta {{comparison['delta_vs_frozen']['map50']:+.3f}}): this adaptation did not help here. The export and reload below still run.\"\n"
                "elif comparison['delta_vs_frozen']['map75'] <= 0:\n"
                "    reading = 'mAP50 rose but mAP75 did not: more boxes carry the right phrase, but they fit no more tightly than before.'\n"
                "else:\n"
                "    reading = 'mAP50 and mAP75 both rose: more boxes carry the right phrase, and they fit more tightly.'\n"
                "outcomes = {{'frozen_beats_grid_prior': frozen_beats_grid_prior, 'frozen_beats_generic_prompt': frozen_beats_generic_prompt, 'adapted_beats_frozen': adapted_beats_frozen, 'adapted_beats_both_baselines': adapted_beats_both_baselines, 'best_epoch': adapt_result['best_epoch']}}\n"
                "print(outcomes)\n"
                "print('Reading: ' + reading)\n"
                "run_history = globals().get('run_history', [])\n"
                "run_history.append({{'run': len(run_history) + 1, 'data': 'BYOD' if USE_BYOD else 'sample', 'epochs': EPOCHS, 'learning_rate': LEARNING_RATE, 'best_epoch': adapt_result['best_epoch'], 'frozen_map50': round(frozen_test['map50'], 3), 'adapted_map50': round(adapted_test['map50'], 3), 'adapted_map75': round(adapted_test['map75'], 3)}})\n"
                "print(f\"{{'run':>3}} {{'data':>6}} {{'epochs':>6}} {{'lr':>8}} {{'best':>4}} {{'frozen':>7}} {{'mAP50':>7}} {{'mAP75':>7}}\")\n"
                "for h in run_history:\n"
                "    print(f\"{{h['run']:>3}} {{h['data']:>6}} {{h['epochs']:>6}} {{h['learning_rate']:>8g}} {{h['best_epoch']:>4}} {{h['frozen_map50']:>7.3f}} {{h['adapted_map50']:>7.3f}} {{h['adapted_map75']:>7.3f}}\")\n"
                "evaluation_report_payload = {{\n"
                "    'model': {{'id': MODEL_ID, 'revision': MODEL_REVISION, 'key': MODEL_KEY}},\n"
                "    'data_source': data_source,\n"
                "    'byod': byod,\n"
                "    'vocabulary': vocabulary,\n"
                "    'generic_prompt': generic_prompt,\n"
                "    'dataset_digests': {{name: manifest['digest'] for name, manifest in dataset_manifests.items()}},\n"
                "    'splits': disjoint,\n"
                "    'split_unit': 'photograph (decoded pixels); no slide or patient field',\n"
                "    'baselines': {{'grid_prior': baseline_grid, 'generic_prompt': baseline_generic}},\n"
                "    'frozen_test': frozen_test,\n"
                "    'validation_metrics': adapted_val,\n"
                "    'test_metrics': adapted_test,\n"
                "    'comparison': comparison,\n"
                "    'outcomes': outcomes,\n"
                "    'reading': reading,\n"
                "    'run_history': run_history,\n"
                "    'adaptation': {{k: v for k, v in adapt_result.items() if k not in ('history', 'trainable_names')}},\n"
                "    'history': adapt_result['history'],\n"
                "    'adaptation_seconds': adapt_seconds,\n"
                "}}\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as f:\n"
                "    json.dump(evaluation_report_payload, f, indent=2, ensure_ascii=False)\n"
                "print({{'report': 'outputs/{stem}_evaluation_report.json'}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the delta rows, the per-phrase rows, the printed reading and the run history.\n\n"
                "<details><summary>Check your reasoning</summary>`platelet`, and nearly. In the recorded T4 run mAP50 rose 0.109 "
                "→ 0.632 and mAP75 0.052 → 0.450 (recall 0.293 → 0.951), past both baselines (0.009 and 0.075): the boxes "
                "tightened, not just the labels. Per phrase, AP50 went `red blood cell` 0.041 → 0.809, `white blood cell` 0.285 → "
                "0.744 and `platelet` 0.000 → 0.343. Platelets are the smallest objects in the photographs and among the rarest "
                "in training, so they give the decoder the least to learn from — and on a small box a few pixels of error are "
                "enough to fall below IoU 0.5. Your run can land a few hundredths away (0.570–0.632 mAP50 across the recorded "
                "runs).</details>\n\n"
                "## 9. Look at the boxes, export the adapter and reload it\n\n"
                "The synthetic scene from Section 5 is detected again by the adapted model — an image family and a vocabulary "
                "the adaptation never saw, so this is a small look at what the adaptation did *outside* its corpus — and four "
                "held-out photographs are written as side-by-side panels (`outputs/{stem}_examples/`: the frozen model's boxes "
                "above `BOX_THRESHOLD`, the adapted model's, and the labelled boxes, coloured by phrase) so the numbers can be "
                "checked by eye: the adapted panels should box the cells the frozen ones missed.\n\n"
                "`pipe.save_artifact` writes the trained tensors — the decoder and the heads, about 45 MB — as "
                "`adapter.safetensors`, with a `manifest.json` recording the artifact format, the base model id and revision, "
                "the digest of the base `model.safetensors`, the tensor names, the file size and SHA-256, the prompt "
                "vocabulary, the training configuration and the epoch history (OUT8). `GroundingDINOPipeline.from_artifact` "
                "re-verifies the base snapshot, checks the artifact manifest, its digest and its exact tensor set **before** "
                "deserialising, refuses any tensor outside the decoder and the heads, and overlays the tensors onto a freshly "
                "loaded base — a new object from files, not the in-memory model (VER2). The cell compares the scored boxes of "
                "the in-memory and the reloaded model on eight test images and stops with an explanation if any differ (VER4).\n\n"
                "**Predict before running:** after tuning the decoder on blood cells, will the adapted model still find the "
                "drawn `rectangle` and `red circle`, and with higher or lower scores than before?"
            ),
            "code": (
                "import shutil\n\n"
                "adapted_scene_result, adapted_scene = detect_scene(pipe, 'adapted')\n"
                "examples_dir = Path('outputs/{stem}_examples')\n"
                "shutil.rmtree(examples_dir, ignore_errors=True)\n"
                "examples_dir.mkdir(parents=True)\n"
                "frozen_base = GroundingDINOPipeline.from_pretrained(weights_dir=WEIGHTS_DIR, device=pipe.device)\n"
                "palette = {{phrase: colour for phrase, colour in zip(vocabulary, [(255, 60, 60), (60, 200, 60), (60, 120, 255), (255, 200, 0), (200, 60, 255), (0, 220, 220)] * 3, strict=False)}}\n\n\n"
                "def box_panel(record, boxes):\n"
                "    panel = record['image'].copy()\n"
                "    marker = ImageDraw.Draw(panel)\n"
                "    for _score, phrase, box in boxes:\n"
                "        marker.rectangle(box, outline=palette.get(phrase, (255, 255, 255)), width=2)\n"
                "    return panel\n\n\n"
                "for record in test_records[:4]:\n"
                "    frozen_boxes = [b for b in frozen_base.predict_boxes(record['image'], vocabulary) if b[0] >= BOX_THRESHOLD]\n"
                "    adapted_boxes = [b for b in pipe.predict_boxes(record['image'], vocabulary) if b[0] >= BOX_THRESHOLD]\n"
                "    labelled = [(1.0, phrase, box) for box, phrase in zip(record['boxes'], record['labels'], strict=True)]\n"
                "    panels = [box_panel(record, frozen_boxes), box_panel(record, adapted_boxes), box_panel(record, labelled)]\n"
                "    width, height = record['image'].size\n"
                "    sheet = Image.new('RGB', (width * 3 + 20, height), (255, 255, 255))\n"
                "    for i, panel in enumerate(panels):\n"
                "        sheet.paste(panel, (i * (width + 10), 0))\n"
                "    sheet.save(examples_dir / f\"{{record['id']}}.png\")\n"
                "frozen_base = None\n"
                "print({{'examples': sorted(p.name for p in examples_dir.iterdir()), 'panel_order': ['frozen boxes >= BOX_THRESHOLD', 'adapted boxes >= BOX_THRESHOLD', 'labelled boxes'], 'colours': palette}})\n\n"
                "artifact_dir = Path('outputs/{stem}_adapter')\n"
                "shutil.rmtree(artifact_dir, ignore_errors=True)\n"
                "pipe.save_artifact(artifact_dir, metadata={{'tutorial': '{stem}', 'data_source': data_source}})\n"
                "artifact_manifest = json.loads((artifact_dir / 'manifest.json').read_text(encoding='utf-8'))\n"
                "print({{'artifact': str(artifact_dir), 'format': artifact_manifest['format'], 'tensors': len(artifact_manifest['tensors']), 'bytes': artifact_manifest['files'][0]['bytes'], 'sha256': artifact_manifest['files'][0]['sha256'][:16] + '...', 'prompts': artifact_manifest['adapter']['prompts']}})\n\n"
                "reloaded = GroundingDINOPipeline.from_artifact(artifact_dir, weights_dir=WEIGHTS_DIR, device=pipe.device)\n"
                "before = [pipe.predict_boxes(r['image'], vocabulary) for r in test_records[:8]]\n"
                "after = [reloaded.predict_boxes(r['image'], vocabulary) for r in test_records[:8]]\n"
                "parity = {{'identical_images': sum(a == b for a, b in zip(before, after, strict=True)), 'of': len(before), 'boxes_per_image': [len(a) for a in before]}}\n"
                "print({{'reload_parity': parity, 'reloaded_best_epoch': reloaded.adapter['best_epoch']}})\n"
                "if parity['identical_images'] != parity['of']:\n"
                "    raise RuntimeError(f'Reload parity failed: {{parity}}. The saved adapter does not reproduce the evaluated model; re-run from Section 7, or restart the session and choose Run all.')\n"
                "reloaded = None\n\n"
                "result_payload = {{\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'model_id': MODEL_ID,\n"
                "    'model_revision': MODEL_REVISION,\n"
                "    'model_license': MODEL_LICENSE,\n"
                "    'snapshot': {{'path': str(WEIGHTS_DIR), 'files': snapshot['files'], 'total_bytes': snapshot.get('total_bytes'), 'fetched_this_run': fetched, 'weight_file': WEIGHT_FILE, 'weight_format': 'safetensors, digest-verified', 'weight_sha256': pipe.weight_sha256}},\n"
                "    'data_source': data_source,\n"
                "    'byod': byod,\n"
                "    'corpus': None if USE_BYOD else {{'name': CORPUS_NAME, 'repo': CORPUS_REPO, 'commit': CORPUS_COMMIT, 'license': CORPUS_LICENSE, 'base_url': CORPUS_BASE_URL, 'bytes': CORPUS_BYTES, 'pinned_images': CORPUS_IMAGES, 'pinned_boxes': CORPUS_BOXES, 'vocabulary': vocabulary}},\n"
                "    'vocabulary': vocabulary,\n"
                "    'inference_contract': {{'input_manifest': input_manifest, 'scene': {{'name': scene_name, 'sha256': scene_sha256, 'prompts': scene_prompts}}, 'frozen_report': frozen_scene, 'adapted_report': adapted_scene, 'output_files': ['outputs/{stem}_scene_frozen.png', 'outputs/{stem}_scene_adapted.png']}},\n"
                "    'generic_prompt': generic_prompt,\n"
                "    'comparison': comparison,\n"
                "    'outcomes': outcomes,\n"
                "    'reading': reading,\n"
                "    'examples': 'outputs/{stem}_examples',\n"
                "    'artifact': {{'dir': str(artifact_dir), 'sha256': artifact_manifest['files'][0]['sha256'], 'bytes': artifact_manifest['files'][0]['bytes'], 'tensors': len(artifact_manifest['tensors'])}},\n"
                "    'reload_parity': parity,\n"
                "    'runtime': {{'python': platform.python_version(), 'torch': torch.__version__, 'transformers': transformers.__version__, 'device': pipe.device, 'dtype': 'float32'}},\n"
                "}}\n"
                "with open('outputs/{stem}_result.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(result_payload, handle, indent=2, ensure_ascii=False)\n"
                "print(sorted(os.listdir('outputs')))"
            ),
        },
    ],
    "closing": (
        "**What to notice:** what changed in the scene's two detections, the four panels in `outputs/{stem}_examples/`, "
        "the artifact's tensor count and size, and the reload-parity line.\n\n"
        "<details><summary>Check your reasoning</summary>Yes, both, with lower scores. In the recorded T4 run the adapted "
        "model still found `red circle` (0.931 → 0.880) and `rectangle` (0.695 → 0.548), with `box_iou` 0.923 and 0.883 "
        "(frozen 0.964 and 0.944): specialising the decoder to three blood-cell phrases cost a little on words it was not "
        "tuned on — one image of evidence, not a measurement. The artifact held 228 tensors, 44,776,600 bytes, and reload "
        "parity was 8/8: the exported adapter is the model that was evaluated. Parity holds because the adaptation started "
        "from the pretrained base, so the adapter carries every tensor that differs from it.</details>\n\n"
        "## 10. Your turn — change one thing: a lower learning rate\n\n"
        "Optional; **Predict → Change one thing → Run → Observe → Explain**. It retrains, so it takes about as long as "
        "Sections 7–9 did (Section 7 alone took 931 s on the T4 record).\n\n"
        "1. **Predict:** with `LEARNING_RATE = 1e-5` (a fifth of the default), will the validation mAP50 climb faster or "
        "slower than the default run's 0.16 → 0.69, will every phrase still improve, and where will the test mAP50 end? Write "
        "your guesses next to the default run's row in the Section 8 run history.\n"
        "2. **Change:** in Section 7 set `LEARNING_RATE = 1e-5`. Change nothing else.\n"
        "3. **Run:** select the Section 7 cell and choose **Runtime → Run after**. Section 7 reloads the pretrained model "
        "before adapting, Section 8 compares against the same Section 6 frozen score and adds a row to the run history, and "
        "Section 9 exports and reloads the new adapter.\n"
        "4. **Observe:** in Section 7, epoch 0 shows the *frozen* validation mAP50 again (0.161 in the recorded T4 run), not "
        "the adapted one — the sign that the model was reset; read how the validation mAP50 moves per epoch. In Section 8, "
        "compare the two rows of the run history, the per-phrase rows and the reading line.\n"
        "5. **Explain:** in one or two sentences, what did the lower rate change, and is the difference between the two runs "
        "larger than the run-to-run spread (0.570–0.632 test mAP50 for the default) and what 94 test images can resolve?\n\n"
        "<details><summary>Check your reasoning</summary>Slower, and not evenly. The build record's raw-API probe of this "
        "rate (four epochs, same split) reached only 0.292 test mAP50, and `white blood cell` drifted *down* on validation "
        "(0.556 → 0.411) while the phrases with many training boxes rose. Expect the same shape over six epochs: a slower, "
        "phrase-uneven climb. The difference from the default (about 0.6) is many times the run-to-run spread, so it is a "
        "real effect of the rate on this split — but it is one split, and your six-epoch numbers are your own "
        "result.</details>\n\n"
        "## Interpretation and limits\n\n"
        "An open-vocabulary detector grounds the words it was trained around, and blood-cell phrases under a microscope are "
        "not among them: the frozen model scores 0.109 mAP50 on BCCD, barely above the model's own boxes for the word `cell` "
        "relabelled to the majority phrase (0.075). A bounded fine-tuning of the decoder and the heads on 220 labelled images "
        "binds the three phrases to the shapes it already proposes (0.632 mAP50 and 0.450 mAP75 in the recorded Kaggle Tesla "
        "T4 run; 0.570–0.632 mAP50 across three recorded GPU runs; `red blood cell` 0.04 → 0.81, `white blood cell` 0.29 → "
        "0.74, `platelet` 0.00 → 0.34), with a 45 MB adapter that reloads box-for-box. That is the claim: the adaptation "
        "contract works end to end on a real labelled set with its own vocabulary, and the numbers it produces are read on two "
        "IoU bars, per phrase, against two non-adapted baselines and the frozen model rather than in isolation.\n\n"
        "The test split is 94 images from one seeded draw of one 364-image set, the validation split that picks the epoch is "
        "50, and both measures are Pascal-VOC average precision at fixed IoU bars over a single-phrase-per-box scoring rule — "
        "not COCO's averaged AP, not `detect`'s text-threshold labelling. The split is by photograph, not by slide, so the "
        "held-out score is an estimate for more photographs of the same set-up. So a gain here says the contract works on "
        "three microscope phrases, not that the adapted model handles other cell types, other stains or magnifications, your "
        "vocabulary, or that its grounding scores are calibrated (they are not, before or after). The rarest and smallest "
        "phrase gained least — a labelled set with a few hundred platelets teaches less than one with thousands of red blood "
        "cells — and fine-tuning on a narrow vocabulary also moves the model elsewhere: the synthetic scene re-detected in "
        "Section 9 kept its two boxes at lower scores, one image of evidence that the adapted decoder now expects blood "
        "cells, not a measurement.\n\n"
        "Three things to carry to real data. **Baselines first:** the grid prior and the generic-prompt relabelling on "
        "*your* labels (with a generic word that fits your objects) are the numbers to read before any adapted one, per "
        "phrase. **Vocabulary:** the phrases the model learns from define what it grounds; spell them the way your "
        "deployment will prompt them, and keep every phrase in the evaluation so a gain on one that costs another is "
        "visible. **Leakage:** keep every image in one split (the contract de-duplicates by decoded pixels) and split by "
        "slide or session when your images come from few sources.\n\n"
        "Successful execution proves that the recorded repository revision's package, carried in this standalone notebook, can "
        "acquire and digest-verify the pinned model snapshot, fetch and digest-verify a real labelled detection set with its "
        "vocabulary, validate the demonstrated dataset contract with no image in two splits, execute the inference contract "
        "and a bounded fine-tuning with the upstream criterion, evaluate against two non-adapted baselines and the frozen "
        "model on an image-disjoint split, and emit the shown machine-readable artifacts — without the repository being "
        "reachable. It does **not** establish benchmark superiority, detection quality on any other vocabulary or imaging, "
        "calibration of the grounding scores, or production fitness.\n\n"
        "**Optional experiments (they do not affect the default path).** Each one changes one thing; note the numbers you "
        "want to compare first (the Section 8 run history keeps one row per pass). In Colab, **Runtime → Run after** runs "
        "the selected cell and every cell below it; Sections 5, 6 and 7 reload the pretrained model before they use it, so no "
        "experiment inherits an earlier adaptation.\n\n"
        "- **A lower learning rate:** Section 10.\n"
        "- **More epochs:** set `EPOCHS = 10` in Section 7, select Section 7 and choose **Run after**. Does the validation "
        "mAP50 keep rising after epoch 6, and which epoch does the selector keep?\n"
        "- **A larger batch:** set `BATCH_SIZE = 8` in Section 7 on a runtime with the memory for it, select Section 7 and "
        "choose **Run after**. With half as many steps per epoch, does the climb slow?\n"
        "- **Synonyms the adapter never saw:** after a full run, add a cell at the end with `synonyms = "
        "dict(zip(vocabulary, ['erythrocyte', 'leukocyte', 'thrombocyte']))` and `pipe.evaluate([{{**r, 'labels': "
        "[synonyms[x] for x in r['labels']]}} for r in test_records], list(synonyms.values()))`, and run only that cell. "
        "What did the adapter do to words it was not tuned on, compared with the per-phrase rows of Section 8?\n"
        "- **Another split:** change `SPLIT_SEED` in Section 4, select Section 4 and choose **Run after**. How far do the "
        "frozen and adapted mAP50 move with a different draw of 94 test images — more or less than the run-to-run spread?\n"
        "- **Your own boxes:** BYOD (Section 4, then **Run after**; set `GENERIC_PROMPT` in Section 6 to the generic word "
        "for your objects). Before the adapted number, how do the two baselines and the frozen model score on your labels?\n\n"
        "## Troubleshooting\n\n"
        "- **Section 1 stops with \"needs a Linux x86_64 runtime\".** The locked environment is built from manylinux wheels. "
        "Use Google Colab, Kaggle or a Linux Jupyter server; Windows and macOS kernels are not supported.\n"
        "- **Section 1 fails while downloading** (`uv` wheel, Python build or packages). The runtime needs PyPI and the "
        "python-build-standalone download; run the cell again once the network is back. A \"size/SHA-256\" or \"does not "
        "match its digest\" error means a file was altered: do not edit the cell, regenerate the notebook from the "
        "repository.\n"
        "- **The run is very slow, or the session ends before Section 9.** On CPU the default path takes hours "
        "(Prerequisites). Switch to a GPU runtime (**Runtime → Change runtime type**) and choose **Run all** again.\n"
        "- **\"The isolated environment's Python process exited\" or a CUDA out-of-memory error.** Usually the runtime ran "
        "out of memory (training peaked near 6 GB of GPU memory at batch size 4, and Section 9 briefly holds two models). "
        "Restart the session and choose **Run all**; in Section 7, `BATCH_SIZE = 2` needs less memory.\n"
        "- **`FileNotFoundError: snapshot file missing` or a `sha256`/`size` `ValueError` in Section 3.** A staged file is "
        "incomplete or altered — delete it from `weights/grounding-dino-tiny/` and run Section 3 again. A photograph digest "
        "mismatch in Section 4 is the same for the cache under `weights/bccd/`; a download error there means GitHub's "
        "raw-content host was unreachable — run Section 4 again.\n"
        "- **BYOD is refused in Section 4.** The message names what to fix: a split with too few images (at least 12 "
        "distinct images in all), two files with one name, an archive over 10,000 files or 1 GB, a missing `boxes.csv`, a "
        "row naming a missing file or with no phrase, a box outside its image, more than 16 phrases, or a duplicate id. Fix "
        "the zip and run Section 4 with **Run after** again. An empty or cancelled upload, or a runtime without the Colab "
        "upload dialog, asks you to choose a file or set `BYOD_PATH`.\n"
        "- **Section 8 reads \"did not help\" or \"The selector kept epoch 0\".** Not an error: under these settings the "
        "adaptation did not beat the frozen model. Read the epoch history in Section 7; the export and reload in Section 9 "
        "still run.\n"
        "- **Reload parity fails in Section 9.** The saved adapter does not reproduce the evaluated model. Re-run from "
        "Section 7 (it reloads the pretrained model first), or restart the session and choose **Run all**.\n"
        "- **Numbers differ from the worked answers.** The frozen numbers move only in the third decimal between GPUs; "
        "training results vary by a few hundredths between runs (Section 7, **Run-to-run spread**). Larger differences on "
        "the default settings mean a form field was changed.\n"
        "- **You re-ran the routing cell in Section 1.** It starts a new isolated process and discards every variable "
        "created so far; choose **Run all** again.\n\n"
        "## Glossary\n\n"
        "- **Open-vocabulary detection:** detection where the classes are given as text at request time instead of being "
        "fixed when the model was trained.\n"
        "- **Prompt vocabulary / phrase:** the list of phrases the model is asked to find; formatted as `phrase. phrase. "
        "phrase.` for the text encoder.\n"
        "- **Query:** one of the 900 box proposals the decoder refines; each query gets a box and a score per phrase.\n"
        "- **Grounding score:** the sigmoid of a query's alignment with a phrase's tokens — a ranking signal, not a "
        "probability.\n"
        "- **`BOX_THRESHOLD` / `SCORE_FLOOR`:** caller-owned cut-offs: `detect` and the panels keep boxes above "
        "`BOX_THRESHOLD`; the corpus measures keep every query whose best phrase reaches `SCORE_FLOOR` (0.05) so the AP "
        "curve sees low-scoring boxes too.\n"
        "- **IoU (intersection over union):** the overlap area of two boxes divided by the area they cover together; 1.0 "
        "is a perfect fit.\n"
        "- **AP50 / AP75:** average precision of one phrase's ranked boxes when a box counts as correct at IoU ≥ 0.5 / ≥ "
        "0.75 with the right phrase; **mAP** is the mean over phrases; **recall50** is the share of labelled boxes found at "
        "IoU ≥ 0.5.\n"
        "- **Grid prior / generic-prompt baseline:** a no-model floor (mean-sized boxes tiled over the image) and the "
        "pretrained model's boxes for one generic word, both labelled with the majority phrase.\n"
        "- **Hungarian matching:** pairs each labelled box with exactly one query (the cheapest one-to-one assignment) so "
        "the loss knows which query should have found which box.\n"
        "- **Focal alignment / L1 / generalised IoU:** the three loss terms — how strongly the matched query aligns with its "
        "phrase's tokens, and how far its box is from the labelled one.\n"
        "- **Epoch / validation selection:** one pass over the training images; the epoch kept is the one with the highest "
        "validation mAP50 (epoch 0 = the frozen model).\n"
        "- **Training / validation / test split:** images used to train, to choose the epoch, and to report the final "
        "result once; split by photograph, so no image is in two splits.\n"
        "- **safetensors / adapter / reload parity:** a tensor file format that cannot run code when loaded; the saved "
        "trained tensors; and the check that a pipeline rebuilt from them and the pinned base gives the same boxes.\n\n"
        "## Conclusion (your notes)\n\n"
        "Optional personal notes, not a required submission. Complete each sentence from your own run:\n\n"
        "- The task: from ___ to ___. On the test images the grid prior scored mAP50 ___, the generic prompt ___, the "
        "pretrained model ___ and the adapted model ___ (kept epoch ___).\n"
        "- mAP75 moved from ___ to ___, so the gain reflects ___ (better labels / tighter boxes / both).\n"
        "- The phrase that gained least was ___, because ___.\n"
        "- One failure mode I saw in the panels: ___. On the synthetic scene, the adaptation changed ___.\n"
        "- A lower learning rate (Section 10) changed ___; the difference between the runs is / is not larger than the "
        "run-to-run spread, because ___.\n"
        "- Before trusting this adaptation on my own images I would measure ___ on ___, split by ___, with the baselines "
        "first.\n\n"
        "## References\n\n"
        "- Repository README: https://github.com/kurtvalcorza/grounding-dino-detection-pipeline/blob/main/README.md\n"
        "- Repository model card: https://github.com/kurtvalcorza/grounding-dino-detection-pipeline/blob/main/MODEL_CARD.md\n"
        "- Weight provenance: https://github.com/kurtvalcorza/grounding-dino-detection-pipeline/blob/main/docs/WEIGHTS.md\n"
        "- Upstream model: https://huggingface.co/{MODEL_ID}\n"
        "- Upstream code: https://github.com/IDEA-Research/GroundingDINO\n"
        "- Grounding DINO: Marrying DINO with Grounded Pre-Training for Open-Set Object Detection (Liu et al., ECCV 2024): https://arxiv.org/abs/2303.05499\n"
        "- BCCD blood-cell detection dataset (MIT): https://github.com/Shenggan/BCCD_Dataset\n"
        "- DIMER Notebook Specification 2.2 and Model Card Specification 1.1 (fleet specs in the ml-worker repository)"
    ),
}
